# Chapter 2 - Math Tools II (Matrices and Operators)

The previous chapter was concluded by describing how one could use a vector to describe a quantum state. This was followed by giving the example of the most basic form of quantum information, a qubit. However, given that a quantum computer's function is to manipulate and evolve a qubit's state according to certain instructions (also called algorithms), it would seem obvious that what we learned isn't sufficient enough to describe quantum information. In quantum mechanics, a system's state is evolved by what is called an operator, and similarly to how vectors are used to describe a system's state, matrices are used to describe how that state evolves once acted upon by an operator. <a href="https://www.numpy.org">Numpy</a> will also be used for Python implementations.

## 2.1 Matrices

In Chapter 1, specifically in the sections related to Dirac Notation, vectors were described by either a column or a row matrix, and matrix multiplication was used to describe inner products. This chapter aims at describing Matrices in more detail and aims at explaining everything you would need to know about matrices to complete this series (which is arguably a complete introduction to basic quantum information theory). A matrix is essentially a 2D, or more specifically, a rectangular array of numbers. A matrix $M$, which has dimensions $m$ and $n$, would look like the following:


   \begin{equation}
  M = \begin{pmatrix} M_{11} & M_{12} & \ldots & M_{1n} \\\ M_{21} & M_{22} & \ldots & M_{2n} \\\ \vdots & \vdots & \ddots &\vdots \\\ M_{m1} & M_{m2} & \ldots & M_{mn}\end{pmatrix}
   \end{equation}


Where the components of the matrix, $M_{ij}$ are numbers (for the sake of this series). If $M_{ij} \in R$, then the matrix is called a real matrix. Similarly, if $M_{ij} \in C$, the matrix is called a complex matrix.

For example, 

   \begin{equation}
  M = \begin{pmatrix} 4 & i & 1 - i \\\ 2 & 0 & 2i\end{pmatrix}
   \end{equation}
   
   is a 2x3 complex matrix. $M_{22}$ = 0, $M_{21} = 2$, etc. 
   
  ### Operations on matrices
  
  **Matrix Addition:**
  
  Condition: Two matrices, $A$ and $B$, with dimensions $m_A \times n_A$ and $m_B \times n_b$, can only be added if $m_A = m_B$ and $n_A = n_B$ (i.e if they have the same dimension).

  Given that they have the same dimensions, their sum would yield the following:
  
  \begin{equation}
  C = A + B \newline C = \begin{pmatrix} A_{11} & A_{12} & \ldots & A_{1n} \\\ A_{21} & A_{22} & \ldots & A_{2n} \\\ \vdots & \vdots & \ddots &\vdots \\\ A_{m1} & A_{m2} & \ldots & A_{mn}\end{pmatrix} + \begin{pmatrix} B_{11} & B_{12} & \ldots & B_{1n} \\\ B_{21} & B_{22} & \ldots & B_{2n} \\\ \vdots & \vdots & \ddots &\vdots \\\ B_{m1} & B_{m2} & \ldots & B_{mn}\end{pmatrix} \newline C = \begin{pmatrix} A_{11} + B_{11}  & A_{12} + B_{12} & \ldots & A_{1n} + B_{1n} \\\ A_{21} + B_{21} & A_{22} + B_{22} & \ldots & A_{2n} + B_{2n} \\\ \vdots & \vdots & \ddots &\vdots \\\ A_{m1} + B_{m1} & A_{m2} + B_{m2} & \ldots & A_{mn} + B_{mn}\end{pmatrix}
  \end{equation}
  
  Or in simpler terms, $C$ is a matrix where $C_{ij} = A_{ij} + B_{ij}$. 
  
  **Matrix Subtraction:**
  
  Condition: Similar to addition, the condition is that the dimensions of matrices $A$ and $B$ are equal
  
   Given that they have the same dimensions, their difference would yield the following:
  
  \begin{equation}
  C = A - B \newline C = \begin{pmatrix} A_{11} & A_{12} & \ldots & A_{1n} \\\ A_{21} & A_{22} & \ldots & A_{2n} \\\ \vdots & \vdots & \ddots &\vdots \\\ A_{m1} & A_{m2} & \ldots & A_{mn}\end{pmatrix} - \begin{pmatrix} B_{11} & B_{12} & \ldots & B_{1n} \\\ B_{21} & B_{22} & \ldots & B_{2n} \\\ \vdots & \vdots & \ddots &\vdots \\\ B_{m1} & B_{m2} & \ldots & B_{mn}\end{pmatrix} \newline C = \begin{pmatrix} A_{11} - B_{11}  & A_{12} - B_{12} & \ldots & A_{1n} - B_{1n} \\\ A_{21} - B_{21} & A_{22} - B_{22} & \ldots & A_{2n} - B_{2n} \\\ \vdots & \vdots & \ddots &\vdots \\\ A_{m1} - B_{m1} & A_{m2} - B_{m2} & \ldots & A_{mn} - B_{mn}\end{pmatrix}
  \end{equation}
  
  Or in simpler terms, $C$ is a matrix where $C_{ij} = A_{ij} - B_{ij}$
  
  
  **Scalar Multiplication:**
  
  Multiplying a scalar $c$ with a matrix $A$ would yield, as with vectors, the same matrix where the components undergo the following transformation: $A_{ij} \rightarrow c*A_{ij}$, or in other words:
  
  \begin{equation}
  B = c*A \newline B = c\begin{pmatrix} A_{11} & A_{12} & \ldots & A_{1n} \\\ A_{21} & A_{22} & \ldots & A_{2n} \\\ \vdots & \vdots & \ddots &\vdots \\\ A_{m1} & A_{m2} & \ldots & A_{mn}\end{pmatrix} \newline B = \begin{pmatrix} cA_{11} & cA_{12} & \ldots & cA_{1n} \\\ cA_{21} & cA_{22} & \ldots & cA_{2n} \\\ \vdots & \vdots & \ddots &\vdots \\\ cA_{m1} & cA_{m2} & \ldots & cA_{mn}\end{pmatrix}
  \end{equation}
  
  **Matrix Multiplication:**
  
  Condition: For two matrices $A$ and $B$ to be multipliable, the following condition must apply: $n_A = m_b$, or in other words, the number of columns in $A$ must be equal to the number of rows in $B$. The result will be an $m_A \times n_B$ matrix. For example, if one is multiplying a $2 \times 4$ matrix by a $4 \times 2$ matrix, it will work out to be a $2 \times 2$ matrix. 
  
  The result of multiplying an $m \times n$ with an $n \times p$ will be
  \begin{equation}
  C = AB \newline C = \begin{pmatrix} A_{11} & A_{12} & \ldots & A_{1n} \\\ A_{21} & A_{22} & \ldots & A_{2n} \\\ \vdots & \vdots & \ddots &\vdots \\\ A_{m1} & A_{m2} & \ldots & A_{mn}\end{pmatrix}\begin{pmatrix} B_{11} & B_{12} & \ldots & B_{1p} \\\ B_{21} & B_{22} & \ldots & B_{2p} \\\ \vdots & \vdots & \ddots &\vdots \\\ B_{n1} & B_{n2} & \ldots & B_{np}\end{pmatrix} \newline C = \begin{pmatrix} C_{11} & C_{12} & \ldots & C_{1p} \\\ C_{21} & C_{22} & \ldots & C_{2p} \\\ \vdots & \vdots & \ddots &\vdots \\\ C_{m1} & C_{m2} & \ldots & C_{mp}\end{pmatrix}
  \end{equation}
  
  where $C_{ij} = A_{i1}A_{1j} + A_{i2}A_{2j} + \ldots A_{in}A_{nj} = \sum_{k=1}^n A_{ik}A_{kj}$.
  
  Note that in practice, it is much easier to get the hang of matrix multiplication than to think of it in terms of a generalized formula, so I'd suggest solving a few matrix multiplication problems to understand what this actually means. It is also important to note that matrix multiplication is not commutative (i.e $AB \neq BA$)
  

  
  **Matrix Division:**
  
  There isn't such a thing. One could argue that the closest thing to matrix division is multiplying a matrix $A$ by a matrix $B$'s inverse, $B^{-1}$. But that will be spoken about in Section 2.2
  
  ### Python Implementation

In [1]:
#Importing necessary modules: numpy can be used to describe matrices in two ways: np.array and np.matrix
#Both were used in Chapter 1, but from now on, we will carry on with np.array
#We'll also import a sympy function so that we can visualize matrices in a clearer way. This does not affect any calculation

import numpy as np
from sympy import Matrix, init_printing

#This function uses SymPy to convert a numpy array into a clear matrix image

def view(mat):
    display(Matrix(mat))

In [2]:
#Defining Matrices

A = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]])
print('4x4 Matrix, A =\n', A)

print('\n')

print('Using SymPy, we can make this look clearer, like this:')
view(A)

#Getting individual components
#A very important thing to note is that python starts counting from 0, so A[2][3] would give us A_34

print('A_34 = ',A[2][3])



4x4 Matrix, A =
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


Using SymPy, we can make this look clearer, like this:


Matrix([
[ 1,  2,  3,  4],
[ 5,  6,  7,  8],
[ 9, 10, 11, 12],
[13, 14, 15, 16]])

A_34 =  12


In [3]:
#Matrix Operation

#Defining two 2x3 matrices, A and B, and one scalar, c
A = np.array([[1,2,0],[1,3,4]])
B = np.array([[4,0,6],[3,0,1]])
C = np.array([[1,0],[9,4],[3,2]])
c = 5

#Addition
print('A+B =')
view(A+B)
print('\n')

#Subtraction
print('A-B = ')
view(A-B)
print('\n')

#Scalar Multiplication
print('cA = ')
view(c*A)
print('\n')
#Multiplication 
print('AC = ')
view(np.matmul(A,C))
print('\n')
#Cocktail
print('-2A + 3B = ')
view(-2*A + 3*B)

#Excersise: Examine Multiplication for matrices A and B, where dim(A) =/= dim(B) 


A+B =


Matrix([
[5, 2, 6],
[4, 3, 5]])



A-B = 


Matrix([
[-3, 2, -6],
[-2, 3,  3]])



cA = 


Matrix([
[5, 10,  0],
[5, 15, 20]])



AC = 


Matrix([
[19,  8],
[40, 20]])



-2A + 3B = 


Matrix([
[10, -4, 18],
[ 7, -6, -5]])

## 2.2 Square Matrices

A matrix that has an equal number of rows and columns is called a square matrix. Its dimensions are described as $n \times n$, where $n$ is what is known as the order of the matrix. For instance, the following matrix is described as a square matrix of order 2:

\begin{equation}
\begin{pmatrix} 1 & 2i \\\ 3 & -1 \end{pmatrix}
\end{equation}
<br>
The diagonal of a square matrix is formed from by set of numbers $A_{ii}$. For example, in the order 2 matrix example above, the diagonal has elements 1 and -1 ($A_{11}$ and $A_{22}$) 
 
 
 Square matrices are very useful for describing linear transformations such as rotation, as well as getting the area formed by a set of vectors. In quantum information theory, a specific type of square matrix called a unitary matrix is used to describe the operators which act on a statevector to change the amplitudes. 
  ### Determinant and Trace
 <br>
 Determinants and traces are operations that are unique to square matrices. The result of a determinant is a number that affects how "scaled" an object is when transformed by a matrix. Similar to matrix multiplication, the general equation of a determinant is usually tedious to look at at first hand, but I'll present the specific cases for $2 \times 2$ and $3 \times 3$ matrices.
 
 For a $2 \times 2$ matrix, $A$, one would find the determinant to be:
 
 \begin{equation}
 det(A) = det\begin{pmatrix} a & b \\\ c & d \end{pmatrix} \newline = ad - bc
 \end{equation}
 
 For a $3 \times 3$ matrix, $A$, one would find the determinant to be:
 
  \begin{equation}
 det(A) = det\begin{pmatrix} a & b & c \\\ d & e & f \\\ g & h & i \end{pmatrix} \newline = a(ei - hf) - b(di -fg) + c(dh - eg)
 \end{equation}
 
 This is all the information I'll be giving on determinants because it is the only information required for this series. However, feel free to investigate this at your own speed. 
 
 <br>
 
 A trace of a square matrix is essentially the sum of all its diagonal's components. Formally, it is written as the following:
 
 \begin{equation}
 Tr(A) = \sum_{i=1}^n A_{ii}
 \end{equation}
  
  In Section 2.1, we described that matrix multiplication is not always commutative, and that in many cases, $AB \neq BA$. However, an interesting property is that $Tr(BA) = Tr(AB)$ regardless of whether the matrices commute or not. As the name suggests, matrices commute when $AB = BA$, and don't commute when $AB \neq BA$.
  
  
 ### Diagonal Matrices
 
 A diagonal matrix is a special case of a square matrix where every element in the matrix is zero except for its diagonal. The following is an example of a $3 \times 3$ diagonal matrix:
 
 \begin{equation}
 \begin{pmatrix} 1 & 0 & 0 \\\ 0 & 3 & 0 \\\ 0 & 0 & 2+i \end{pmatrix}
 \end{equation}
 
 ### Triangular Matrices
 It is said that the diagonal divides the matrix into two blocks. The upper block, consists of all elements, $A_{ij}$ where $i \leq j$. Similarly, the lower block consists of all $A_{ij}$ where $i \geq j$. An upper triangle matrix is any matrix where the upper block consists of any set of numbers and the lower block consits of only zeros. In other words, it is any matrix that takes the following form:
 
   \begin{equation}
  M = \begin{pmatrix} M_{11} & M_{12} & \ldots & M_{1n} \\\ 0 & M_{22} & \ldots & M_{2n} \\\ \vdots & \vdots & \ddots &\vdots \\\ 0 & 0 & \ldots & M_{nn}\end{pmatrix}
   \end{equation}
   
   Matrix $A$ is a $4 \times 4$ example:
   
   \begin{equation}
  M = \begin{pmatrix} M_{11} & M_{12}  & M_{13} & M_{14} \\\ 0 & M_{22} & M_{23} & M_{24} \\\ 0 & 0 & M_{33} & M_{34} \\\ 0 & 0 & 0 & M_{44}\end{pmatrix}
   \end{equation}
<br>
  On the other hand, we also have lower triangle matrices, where $A_{ij} = 0$ if $i>j$. It takes the following form:
  
 <br>
  
   \begin{equation}
  M = \begin{pmatrix} M_{11} &0 & \ldots & 0 \\\ M_{21} & M_{22} & \ldots & 0 \\\ \vdots & \vdots & \ddots &\vdots \\\ M_{m1} & M_{m2} & \ldots & M_{mn}\end{pmatrix}
   \end{equation}


   Matrix $B$ is a $4 \times 4$ example:
    
   \begin{equation}
  M = \begin{pmatrix} M_{11} & 0  & 0 & 0 \\\ M_{21} & M_{22} & 0 & 0 \\\ M_{31} & M_{31} & M_{33} & 0 \\\ M_{41} & M_{42} & M_{43} & M_{44}\end{pmatrix}
   \end{equation}

A diagonal matrix can be viewed as either an upper or lower matrix
 
 ### Identity Matrix and Matrix Inversion
 
 An identity matrix, $I$, is any matrix where its diagonal elements are all equal to 1 and the rest of the elements are equal to 0. Formally, it could be represented by the Kronicker-Delta function described in Section 1.9 in the following way:
 
 \begin{equation}
 I_{ij} = \delta_{ij}
 \end{equation}
 
 where $\delta_{ij}$ is
 \begin{equation}
\delta_{ij} =
    \begin{cases}
            1, &         \text{if } i=j,\\
            0, &         \text{if } i\neq j.
    \end{cases}
\end{equation}

The following is a $3 \times 3$ identity matrix, $I_3$:


\begin{equation}
I_3 = \begin{pmatrix} 1 & 0 & 0 \\\ 0 & 1 & 0 \\\ 0 & 0 & 1\end{pmatrix}
\end{equation}

 
 One of the most notable properties of the identity matrix is that when any matrix $A$ is multiplied with it,  the results will be the same matrix. In other words, for an $m \times n$ matrix,
 
 \begin{equation}
 I_m A = AI_n = A
 \end{equation}
 
 and for a square matrix, the order of multiplication with the identity won't matter because $n = m$.
 
 
 In Section 1, an important point that was stated is that there is no such this as matrix division but that for square matrices, one can get its inverse $A^{-1}$, where
 
  \begin{equation}
  AA^{-1} = I
  \end{equation}
  
 
 

In [4]:
#Defining square matrices

A = np.array([[3,0,2], [2,0,-2],[0,1,1]])

#Determinant and Trace

trA = A.trace()
detA = np.linalg.det(A)

print('A = ')
view(A)

print('Tr(A) = ', trA)
print('det(A)', detA)

print('')
#Identity and Inverse

Ainv = np.linalg.inv(A)

#Multiplying A with its inverse. The result should be the I_3

print('I = AA^-1 = ')
view(np.matmul(A,Ainv))

print('The result is the identity. I_21 is approximately zero and is not exactly zero because of some negligable numerical error')

#Excercise: Create a function that identifies whether a square matrix is a diagonal matrix, upper triangle or lower triangle


A = 


Matrix([
[3, 0,  2],
[2, 0, -2],
[0, 1,  1]])

Tr(A) =  4
det(A) 10.000000000000002

I = AA^-1 = 


Matrix([
[                  1.0, 0.0, 0.0],
[-5.55111512312578e-17, 1.0, 0.0],
[                  0.0, 0.0, 1.0]])

The result is the identity. I_21 is approximately zero and is not exactly zero because of some negligable numerical error


## 2.3 Operators

As you most likely know, a function is a mathematical object that transforms an input number into an output number. Similarly, an operator is a mathematical object which transforms a function into a whole other function. An example is the derivative, which yields the rate at which a function is changing. The definition of an operator could be extended to vectors. In other word, an operator maps a vector $|v_1>$ to a new vector $|v_2>$. Notationally, this could be written as follows:

\begin{equation}
A|v_1> = |v_2>
\end{equation}

Where $A$ is an operator, $|v_1>$ is the "input " vector and $|v_2>$ is the "output vector".

In a quantum system, an operator $A|\psi>$ can represent an observable, which is essentially a physical quantity such as momentum and position. More specifically, an observable must be a linear operator, which we'll speak about soon.

### Operator Algebra

Let us say we have operators $A$ and $B$ acting on vector $|\psi>$. The following rules must apply:

**Adding operators:**

\begin{equation}
(A+B)|\psi> = A|\psi> + B|\psi>
\end{equation}

**Multiplying two operators (on state):**

\begin{equation}
(AB)|\psi> = A[B|\psi>]
\end{equation}

**Multiplying three operators:**

\begin{equation}
A(BC) = (AB)C
\end{equation}


**Commuation:**
\begin{equation}
[A,B]|\psi> = AB|\psi> - BA|\psi>
\end{equation}


If a $[A,B]|\psi> = 0$, then the operators commutate and if $[A,B]|\psi> \neq 0$, then the operators don't commutate. This is similar to what was mentioned in 2.2. Commutation has a very important physical implication in quantum mechanics that will be described in Chapter 3.


### Linear Operators

An operator, $A$, was defined to be an object that transforms a vector $|v_1>$ to $|v_2>$. If vectors $|v_1>$ and $|v_2>$ are in the same vector space **V**, then $A$ is said to be a linear operator. Notationally, linear operator $A$,  is represented as follows:

\begin{equation}
A|v_1> = |v_2> ; |v_1>, and |v_2> \in V
\end{equation}
<br>
If $A$ is a linear operator, than it must have the following properties:

      1. A(|u> + |v>) = A|u> + A|v>
      2. A(c|u>) = cA|u>
and finally, from 1 and 2:
      
      3. A(c|u> + d|v>) = rA|u> + dA|v> 
      
Where $c$ and $d$ are some constants and $c|u> + d|v>$ is a linear combination. In other words, an operator acting on a linear combination of vectors is equal to a linear combination of the vectors produced by the act of applying the operator on them.  

In [23]:
#Operator of a function where O[f(x)] = f(x)*2 + 3
#If you don't know what a lambda function is in Python, check it out here: https://www.w3schools.com/python/python_lambda.asp

def operator(f):
    newFunc = lambda x: f(x)*2 + 3
    return newFunc

#g(x) = O[f(x)], where f(x) = 2*x. The result should be 4x + 3
#g(3) = 4*3 + 3 = 15


g = operator(lambda x: 2*x)

print('g(x) = O[f(x)] = O[2x] = 2*2x + 3 = 4x+3')
print('g(3) = 4*3 + 3 = ', g(3))

#Excercise: Create a derivative(f) operator that gets the derivative of an input function



g(x) = O[f(x)] = O[2x] = 2*2x + 3 = 4x+3
g(3) = 4*3 + 3 =  15


In [12]:
#Operator of a vector where A|u> = |v>, where v_i = 2 u_i + 3

def operator(vec):
    newVec = np.array([2*i + 3 for i in range(len(vec)+1)])
    return newVec
    

u = np.array([1,2,3,4])
v = operator(u)

print('|u> = ', u)
print('')
print('|v> = O|u> = ', v)

#Excersise: Create linChecker(operator) function to check if an operator O is linear or not

|u> =  [1 2 3 4]

|v> = O|u> =  [ 3  5  7  9 11]


In [88]:
#Commutation: Creating a function that checks whether operators A and B commutate on some dummy function f(x) = 2*x

#[A,B](2x) =?= 0
def commutate(A,B):
    f = lambda x: 2*x
    if lambda x: A(B(f))(2) == B(A(f))(2):
        print('A and B commute!')
    else:
        print('A and B do not commute!')
    
        
def A(f):
    newFunc = lambda x: f(x)**2
    return newFunc

def B(f):
    newFunc = lambda x: np.log(f(x))
    return newFunc

commutate(A,B)

A and B commute!


## 2.4 Matrix Representation of Linear Operators

## 2.8 Symmetric Matrix

## 2.9 Transpose

## 2.10 Orthogonal Matrices

## 2.11 Identity Operator

## 2.12 Adjoint Operator

## 2.13 Hermition Operator

## 2.14 Unitary Operators

## 2.15 Projection Operators